server:
  port: 8085

spring:
  application:
    name: CONFIG-PROD

  cloud:
    config:
      server:
        git:
          uri: https://github.com/YASWANTHBHERI/Microservices-ConfigServer
          clone-on-start: true
